version: "3"

services:
  # image project
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # db mysql
  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-envio-whatsapp}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-envio-whatsapp}
      MYSQL_PASSWORD: ${DB_PASSWORD:-envio-whatsapp}
      MYSQL_USER: ${DB_USERNAME:-envio-whatsapp}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3300:3306"
    networks:
      - laravel

  # redis
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"
    networks:
      - laravel
      - default

  api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - 8081:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - laravel
    env_file:
      - .env.evolution

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evolution_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - laravel
      - default

volumes:
  evolution_instances:
  pg_data:

networks:
  laravel:
    driver: bridge
